### ISSUE TITLE
Search extending too far

### ISSUE THREAD

**Issue by jason-ziptrak** [andriimisiats/find-a-retailer#2]
![too far out of range2](https://user-images.githubusercontent.com/38022902/38225066-40e0a220-3732-11e8-8809-2542f2e3d286.jpg)
![too far out of range](https://user-images.githubusercontent.com/38022902/38225067-4122cb64-3732-11e8-9da5-4575e2af6b6f.jpg)

It seems the usence Find a Retailer is searching a longer distance than the Geolocator currently installed on the live website. It's causing it to pull listings in from 30+ kms away, in scenarios where they are closer results. The two systems do not appear to be acting the same, although the settings are the same.

**Comment by andriimisiats** [comment]
Hi Jason,

Thank you for this issue.

I tested Find-a-Retailer plugin and find similar situation. Then I checked settings for Find-a-Retailer plugin and find, that maximum distance for non-premium retailers equals 150 km.

**Comment by jason-ziptrak** [comment]
Hi Andrey, 

It still does not make much sense to me. Searching Ironbank - I see the two retailers, and understand how it picks them up. It then shows House of Allure which is very very far away, but within 150km. House of Allure has a priority of 1. You set this for I think all listings, correct? Is there a reason? 

I don't understand why the system chooses House of Allure which is much further away then 47 of the other retailers. I think its just totally random, because if I keep clicking search, then it keeps throwing up random options. The issue here is that choosing the result, line of sight, was actually a good system instead of collecting all retailers within 150km and presenting randomly, like we are doing now, if they are all same priority. I will need to speak with Marc about this. Do you have ideas?

**Comment by andriimisiats** [comment]
Hi Jason,

All retailers had a priority of 1. 
I can see, that you changed some priorities on test hosting.

Yes, the system gets all retailers within 150 km and sorts it by priority. I used this algorithm:
![image](https://user-images.githubusercontent.com/26199758/38352357-92b9f1de-38bb-11e8-90ca-d992849716c7.png)

I can rewrite the algorithm:
In first 10 km (standart search distance), system will search retailers and sort by priority.
Then, if number of retailer will be less than 4 (number of results displayed), system will find the closest retailers in 150 km(max search distance), and sort by DISTANCE.

E.G.
System searchs within 10 km and finds 2 retailers. Sorts retailers by priority. Displays 2 retailers.
Then system searchs within 150 km and finds 47 retailres. But sorts by distance and displays another 2 retailers.

**Comment by jason-ziptrak** [comment]
Hi Andrey, 

Thanks for these comments. You have referred to point E page 17 on document: ZDOC0116_05 - Website Enhancements Requirements.docx. 

In point C (same page) we wrote requirements on how the system is to SELECT/CHOOSE retailers. Point E then talks about how to DISPLAY retailers. Please read page 17 over again, and specifically point C. Your message above, where you speak about rewriting the algorithm, is the same as what the document requirements are. 

Is anything still unclear?

**Comment by andriimisiats** [comment]
Hi Jason,
Thank you.
The system worked this way (how it described in point C) before the update (priority function).
I will rewrite it again soon.

**Comment by andriimisiats** [comment]
Hi Jason,
I rewrote the algorithm.
Please, test it one more time.

Thank you!

**Comment by jason-ziptrak** [comment]
Hi Andrey, all my testing is showing that this is working. Thanks for your efforts. Have you done some testing yourself too?

**Comment by andriimisiats** [comment]
Hi Jason,
Good to hear it.
I tested it with locations, described above and another 5-10 locations.
Looks, like we don't have a problem here now.

Thank you!

**Comment by jason-ziptrak** [comment]
Thanks Andrey - all good. Confirmed to be working.
