### ISSUE TITLE
Spacing between Products + Store Type

### ISSUE THREAD

**Issue by jason-ziptrak** [andriimisiats/find-a-retailer#4]
![spacing improvement](https://user-images.githubusercontent.com/38022902/38598003-c9ab36c0-3d99-11e8-8053-f696c277582a.jpg)

Hi Andrey, 

When the Store Type stacks onto the Product Type, when using a mobile or smaller screen, in our opinion there is not enough white space as a gap between the two items. Could you please arrange to increase this gap by a few pixels? Thank you.

**Comment by andriimisiats** [comment]
Hi Jason,

Sorry for my slow response. Sometimes, I don't receive notifications about your comments.
I increased the gap. Result:
![image](https://user-images.githubusercontent.com/26199758/38780469-8a9b6556-40df-11e8-891f-c3206a3c9355.png)

Thank you!

**Comment by jason-ziptrak** [comment]
Thank you, this is approved and my testing has confirmed its working.
