### ISSUE TITLE
Map information - icons missing

### ISSUE THREAD

**Issue by jason-ziptrak** [andriimisiats/find-a-retailer#5]
![issue with icons within map descriptions](https://user-images.githubusercontent.com/38022902/38790078-c1638df4-417d-11e8-9bf1-df32bea38b9e.jpg)

**Comment by jason-ziptrak** [comment]
Hi Andrey, please see the word "all" appearing, instead of the icons. It should look like how it does currently on the Australian site: 
![no issue with icons within map descriptions](https://user-images.githubusercontent.com/38022902/38790109-fb814d3c-417d-11e8-8ce2-934a3c8060ca.jpg)

**Comment by andriimisiats** [comment]
Hi Jason,

Thank you! I fixed it, added gaps and products.
![image](https://user-images.githubusercontent.com/26199758/38834631-af0e0e64-41d1-11e8-9ebc-bfc28c3b46a5.png)

**Comment by jason-ziptrak** [comment]
Ok thanks, confirmed to be working.
